### ISSUE TITLE
All Hands 2020: Draft Agenda Items

### ISSUE THREAD

**Issue by jamesmunns** [rust-embedded/wg#381]
Placeholder

**Comment by japaric** [comment]
For reference, this year (RAH 2019) we had 2 1-hour meetings and one 2-hour working session. Notes and attendance can be found at https://paper.dropbox.com/doc/WG-Embedded-Rust-All-Hands-2019-Topics--Ams~zlHKeJ911vGs6mM1Vn~YAg-JrPzUM1Z3SC859MS03lfC

**Comment by Dylan-DPC** [comment]
Following this issue for coordination purposes.

**Comment by jonas-schievink** [comment]
My two cents:

`T-lang` inquiries:

* Specify what `Send` and `Sync` mean without using the word "thread"
  * Embedded Rust uses "thread-equivalent" constructs such as interrupt handlers, and also has less equivalent constructs such as multi-core MCUs. It would be good to know what `Send` and `Sync` *really* mean, since their contract can't be specific to just threads.
* Reconsider [RFC 2492](https://github.com/rust-lang/rfcs/pull/2492) ("Existential types with external definition") as it would allow using the same mechanism for allocators, panic handlers, and other embedded-specific things (which would be?)

`T-compiler` inquiries:

* How do we get the bug fixed where LLVM thrashes the link register? https://github.com/rust-embedded/cortex-m-rt/issues/139
  * I think there's still no upstream bug for this, so this is basically our fault

`T-infra` inquiries:

* How much room is there on dist-various-1 for embedded targets? Currently that builder runs all embedded tests even though it's not really meant for that I think. (failures also don't show up in PR builds, only in bors)

**Comment by jamesmunns** [comment]
All hands didn't happen this year. Closing.
