### ISSUE TITLE
Agenda for 2019-12-10 meeting

### ISSUE THREAD

**Issue by japaric** [rust-embedded/wg#403]
[8-9 PM CET][0] (Berlin time) on [#rust-embedded:matrix.org](https://matrix.to/#/#rust-embedded:matrix.org)

[0]: https://everytimezone.com/?t=5deee000,474

[Public Google calendar that includes these weekly meetings](https://calendar.google.com/calendar?cid=NzhmdGJsMGQ1cjA2YzM5dDJ1MDU0ODBsbm9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

## Agenda 

- The big picture of embedded-hal / re-organizing embedded-hal. cc @thejpster 

- Motivation for book monorepo proposal -- @ghost (who proposed this?)

- Digital v3 (voting? idk) -- @Disasm (?)

- [your topic goes here]

---

This meeting is open for anyone to attend. If you'd like to bring up any issue / topic related to embedded Rust leave a comment in this issue so we can add it to the agenda.

**Comment by jamesmunns** [comment]
Current CI testing is a No-Op: https://github.com/rust-lang/rust/issues/67018

**Comment by thejpster** [comment]
Some guidance on https://github.com/rust-embedded/cortex-m-quickstart/pull/78 would be useful. How do we feel about IDE specific additions to quickstart? Would we take an Intelli-J IDEA project, or a Sublime Text project?

**Comment by rubberduck203** [comment]
Some context for that conversion @thejpster 

<img width="636" alt="Screen Shot 2019-12-06 at 6 07 54 AM" src="https://user-images.githubusercontent.com/2716800/70318798-dd428180-17ee-11ea-9973-445f6f4ef5e7.png">

https://www.jetbrains.com/lp/devecosystem-2019/rust/

**Comment by jonas-schievink** [comment]
That PR adds configuration for very specific MCUs, for use with a specific VSCode plugin, not all VSCode users will benefit from that.

Another agenda item: https://github.com/rust-embedded/cortex-m-rt/issues/223 (regression in the cortex-m-rt release).

**Comment by rubberduck203** [comment]
@jonas-schievink I didn’t intend to imply that it would. Only providing some editor usage data to frame the conversation.

**Comment by IGBC** [comment]
Can we chuck Generic Radio Traits on the agenda?
We have a few driver crates for various radio standards, but when building a protocal ontop of those and making them driver agnostic it would be nice to have a trait for each radio standard (LoRa, Zigbee, Bluetooth, WiFi, whatever) to bind to instead.

**Comment by therealprof** [comment]
> Can we chuck Generic Radio Traits on the agenda?

You can put pretty much anything on the agenda but unless you have a proposal it's not very likely that this will result in fruitful discussion since these topics require a high level of domain specific knowledge. It would probably be better to form a group exploring the options and the way forward leading to an RFC proposing those traits and then put it on the agenda for discussion.

**Comment by IGBC** [comment]
welp. I will not claim to be experienced in the area.

**Comment by ryankurte** [comment]
> Can we chuck Generic Radio Traits on the agenda?

@IGBC i've been working on this for a while now for ISM / LoRa stuff, not sure about how it'd work with WiFi which (afaik) it'd be unusual to interact with as a radio (rather than via some kind of socket API).

You might be interested in [previous discussion](https://github.com/rust-embedded/embedded-hal/issues/48) in embedded-has, some discussion on [rubble](https://github.com/jonas-schievink/rubble/issues/48), and my WIP [implementation](https://github.com/ryankurte/rust-radio) (which links out to a set of implementers). I haven't looked at extracting commonality for configuration yet, but the operation of all of em is the same.

If you'd like to talk about it more we could re-open the HAL issue as a place to chat.

**Comment by Disasm** [comment]
Sorry, I will not be able to attend the meeting. As for the `digital::v3`, I'd rather postponed the voting until we agree on the future structure of the `embedded-hal` crate.

**Comment by thejpster** [comment]
I'm afraid I've been off sick most of the last week, so I haven't written up the RFC yet.
